id: P005471
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:52:20.138276
source_metadata:
  id: bdr:W1PD137879
  title: གསུང་འབུམ། རྒྱལ་དབང་བསོད་ནམས་རྒྱ་མཚོ།
  author: ''
  volumes:
    9516b2fb749c4137ac2c940296427147:
      image_group_id: I2PD18687
      title: ''
      volume_number: 1
      total_pages: 410
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
